assets:
  settings.xml: "yegor256/home#assets/aintshy/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  id_rsa: "yegor256/home#assets/aintshy/id_rsa"
  id_rsa.pub: "yegor256/home#assets/aintshy/id_rsa.pub"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

install:
  - "sudo gem install pdd"

deploy:
  script: |
    mvn clean deploy -Paintshy --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=aintshy-hub.xml
    s3cmd --no-progress put aintshy-hub.xml --config=../s3cfg s3://pdd.teamed.io/aintshy-hub.xml

release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mv ../settings.xml settings.xml
    mvn clean install -Pqulice --errors
    mvn liquibase:update -Paintshy --errors --settings settings.xml
    git remote add heroku git@heroku.com:aintshy.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add settings.xml
    git commit -m 'settings.xml'
    git push heroku "${tag}"
    curl http://i.aintshy.com -f

merge:
  script: |
    mvn help:system clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null

