language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
before_install:
  - unset GEM_PATH
branches:
  only:
    - master
script:
  - mvn clean install -Pqulice

